### ISSUE TITLE
3.7 Slider - first attempt

### ISSUE THREAD

**Issue by bekqs** [tutsplus/30-days-to-jquery#2]
Hi. I had a little problem understanding why the following code worked for you but for me it didn't, even though I was following your video. Point me if I missed anything.
This is the code from the video, which didn't work for me, because:
`loc = totalImgsWidth(2400) - imgWidth(600) = 1800px(positive number)`

then I changed it to:
`loc = -totalImgsWidth(-2400) + imgWidth(600) = -1800px.`
And it worked. 
```
if(current === 0) {
            current = imgsLen;
            loc = totalImgsWidth - imgWidth;
            direction === 'next';
        } else if(current - 1 === imgsLen) {
            current = 1;
            loc = 0;
        }
```

Thanks.

**Comment by ghost** [comment]
My mistake. I wrote direction === 'next' instead of direction = 'next'.
